version: '3.9'

services:
  rtmp:
    build:
      context: .
      dockerfile: Nginx-rtmp/Dockerfile
    ports:
      - 1935:1935

  user:
    build:
      context: .
      dockerfile: Back/user/Dockerfile
    ports:
      - "1331:1331"
    depends_on:
      - db-user

  web:
    build:
      context: .
      dockerfile: Front/Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
      # - app

  # app:
  #   image: myapp:latest
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db/myapp
  #   depends_on:
  #     - db

  db-user:
    image: postgres:16
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data-user:/var/lib/postgresql/data

volumes:
  db-data-user: